sudo: false
language: node_js
services:
- docker
branches:
  only:
  - dev
  - master
matrix:
  fast_finish: true
  include:
  - node_js: '12'
# https://github.com/greenkeeperio/greenkeeper-lockfile#npm
before_install:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_06af7147f9c8_key -iv $encrypted_06af7147f9c8_iv
    -in ${TRAVIS_BUILD_DIR}/ci/kubernetes-external-secrets.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
  # package-lock.json was introduced in npm@5
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
  - npm install -g greenkeeper-lockfile
  # kubectl, kind, helm
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-linux-amd64
    && chmod +x kind && sudo mv kind /usr/local/bin/
  - curl -Lo helm.tgz https://get.helm.sh/helm-v2.16.0-linux-amd64.tar.gz && tar -zxvf
    helm.tgz && sudo mv linux-amd64/helm /usr/local/bin/helm
install: npm install
#before_script: 'if [[ ${TRAVIS_BRANCH} == "master" &&  ${TRAVIS_PULL_REQUEST} == "false" ]]; then bash release.sh; fi'
script:
  - npm test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test-e2e; fi'
  - helm lint charts/kubernetes-external-secrets
#after_script: 'if [[ ${TRAVIS_BRANCH} == "master" &&  ${TRAVIS_PULL_REQUEST} == "false" ]]; then bash release.sh; fi'
after_success:
  - 'if [[ ${TRAVIS_BRANCH} == "master" &&  ${TRAVIS_PULL_REQUEST} == "false" ]]; then bash release.sh; fi'

